FROM python:3.10.4-slim-buster

COPY db ./db

WORKDIR /python

COPY python/main.py main.py

COPY python/image image

COPY python/requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000"] 